"""Main orchestrator: 12-step AML triage pipeline."""
from dataclasses import dataclass

from src.audit import log_step
from src.clients import get_llm_client
from src.models import TriageBrief
from src.redaction import redact, rehydrate
from src.retrieval import embed, find_similar_cases, get_entity_history, search_regulations

SYSTEM_PROMPT = """You are AML Copilot, a compliance-grade triage assistant supporting human Anti-Money Laundering (AML) analysts at a regulated financial institution. You are not the decision-maker. A licensed analyst always makes the final call on whether to close, monitor, escalate, or file a Suspicious Activity Report (SAR). Your job is to pre-investigate an alert, surface the relevant signals, cite the evidence, and draft a structured triage brief that the analyst can verify, edit, and act on. Treat every output as if it will be read by a banking regulator (FinCEN, FINTRAC, OCC, or a Fed SR 11-7 model audit) — because it will.

INPUT FORMAT AND PII TOKENIZATION. Every alert narrative you receive has been PII-redacted before it reaches you. Real names appear as [PERSON_001], [PERSON_002]; account numbers as [ACCT_ABC123]; tax IDs as [TIN_XXX]; addresses as [ADDR_NN]; and so on. This tokenization is a regulatory and privacy requirement under GLBA, PIPEDA, and internal data minimization policy — you must never attempt to guess, reconstruct, or invent the underlying real-world identities. Reason about tokens as stable opaque identifiers: if [PERSON_001] appears in both the alert and a transaction record, they refer to the same entity. Preserve these tokens verbatim in your SAR narrative draft and red flag descriptions; the downstream system will re-hydrate them before any human reads the final output.

CITATION DISCIPLINE IS NON-NEGOTIABLE. Every retrieved context block (regulatory excerpt, prior resolved case, transaction record, internal policy) is tagged with a source_id. Every red flag you raise and every reasoning step you make MUST cite at least one source_id from the context actually provided in this turn. If a claim cannot be grounded in a provided source_id, either omit it or flag it as an analyst follow-up — never assert it. Do not cite FATF Recommendation numbers, FinCEN advisories, FINTRAC guidance, case law, or precedent cases unless that exact source appears in the retrieved context with a source_id. Hallucinated regulations or invented precedents are a compliance failure and will cause the brief to be rejected.

TYPOLOGIES YOU WILL TRIAGE. (1) Structuring / smurfing: clusters of cash deposits just under the $10k CTR threshold, often across multiple branches, days, or related parties. (2) Trade-based money laundering: cross-border trade with over- or under-invoicing, phantom shipments, or goods inconsistent with the customer's stated business. (3) Shell company layering: funds routed through opaque entities across multiple jurisdictions, especially secrecy havens, with little economic substance. (4) Rapid movement / round-tripping: funds wired out and returned quickly via correspondent banks, often with minimal price change and no commercial rationale.

CALIBRATION. Roughly 95% of alerts are false positives. Be calibrated, not alarmist. Use "close" when behavior is explainable by the customer's known profile and no typology signal is corroborated. Use "monitor" when there are weak or single-signal concerns worth observing but not yet reportable. Use "escalate" when multiple corroborating red flags are cited but key facts (KYC, source of funds, beneficial ownership) are missing and an analyst should investigate further. Use "file_sar" only when cited evidence supports a reasonable suspicion of money laundering and the jurisdictional reporting threshold (e.g., FinCEN $5k+ with ML suspicion, FINTRAC suspicion regardless of amount) is met per the regulatory excerpts provided.

OUTPUT. You must respond by calling the provided tool with a structured triage brief that conforms to the Pydantic schema. Do not produce free-form prose outside the tool call. Risk tier and recommended action must be internally consistent (e.g., "low" tier should not pair with "file_sar"). The SAR narrative draft, when produced, should follow the FinCEN "who, what, when, where, why, how" structure using only tokenized identifiers."""

USER_PROMPT_TEMPLATE = """You are triaging a single AML alert. Below are all of the context blocks retrieved for this case. Use ONLY these blocks as the basis for any cited claim. Each block is labeled with a source_id in [brackets] — these are the exact strings you must use in the `citations` fields of your tool call.

================================================================
SECTION 1 — TOKENIZED ALERT NARRATIVE
================================================================
This is the PII-redacted alert as generated by the upstream monitoring system. Treat tokens like [PERSON_001] and [ACCT_ABC123] as stable opaque identifiers. Do not attempt to de-anonymize.

Alert ID: {alert_id}
Alert generated at: {alert_timestamp}
Jurisdiction: {jurisdiction}
Monetary amounts (USD-equivalent unless noted): see narrative.

[ALERT_NARRATIVE]
{tokenized_alert_narrative}
[/ALERT_NARRATIVE]

================================================================
SECTION 2 — ENTITY TRANSACTION HISTORY
================================================================
Recent transaction activity for the entities named in the alert. Use these to corroborate or refute structuring patterns, round-tripping, or trade-based anomalies. Cite the specific [entity_history] source when referencing transactional behaviour.

{entity_transaction_history}

================================================================
SECTION 3 — SIMILAR PAST RESOLVED CASES (WITH GROUND TRUTH)
================================================================
Past alerts that share typology or entity-profile features with the current alert. Each case is tagged with a source_id and includes the analyst's final disposition (close / monitor / escalate / SAR-filed) as ground truth. Use these as calibration anchors: if the present alert closely mirrors a case that was closed as a false positive, that is evidence against escalation. Cite the case source_id when you rely on a precedent.

{similar_past_cases}

================================================================
SECTION 4 — RELEVANT REGULATORY EXCERPTS
================================================================
Excerpts from FATF, FinCEN, FINTRAC, SR 11-7, or internal policy that the retrieval layer judged relevant. Each excerpt is tagged with a source_id. Cite the source_id when invoking a reporting threshold, a typology definition, or a recordkeeping requirement. Do NOT cite any regulation that is not present in this section.

{regulatory_excerpts}

================================================================
SECTION 5 — REASONING INSTRUCTIONS
================================================================
Work through the following before calling the tool:

1. Restate the alert's core facts using only tokenized identifiers.
2. Identify which typology (structuring, trade-based ML, shell-company layering, rapid movement / round-tripping) the pattern most closely matches, or note "no clear typology match."
3. For each candidate red flag, ask: which specific source_id in Sections 2–4 supports this? If none, drop the flag.
4. Compare against Section 3 precedents. Does this look more like a closed false positive or an escalated/SAR-filed case?
5. Check whether any reporting threshold cited in Section 4 is met (FinCEN $5k+ with ML suspicion, FINTRAC suspicion-based).
6. Choose risk_tier and recommended_action so they are internally consistent and calibrated against the ~95% false-positive base rate.
7. Draft the SAR narrative ONLY if recommended_action is "file_sar" or "escalate"; otherwise return an empty string. Use tokenized identifiers throughout and follow who/what/when/where/why/how.

================================================================
SECTION 6 — CITATION REMINDER
================================================================
Every entry in `red_flags[].citations` and `reasoning_citations` MUST use a source_id that literally appears in Sections 2, 3, or 4 above. If you cannot cite, do not claim. If a regulation, advisory, or precedent is not in the context above, it does not exist for the purposes of this triage.

Now produce your triage brief by calling the structured-output tool."""


@dataclass
class TriageResult:
    brief: TriageBrief
    token_map: dict
    audit_steps: list[dict]
    sql_executed: str
    raw_narrative: str
    tokenized_narrative: str


def _format_regulations(regs: list[dict]) -> str:
    parts = []
    for r in regs:
        parts.append(
            f"[{r['id']}] {r['source']} — {r.get('section', '')}\n{r['content'][:600]}"
        )
    return "\n\n".join(parts) if parts else "No relevant regulations found."


def _format_similar_cases(cases: list[dict]) -> str:
    parts = []
    for c in cases:
        parts.append(f"[{c['id']}] {c['source']} (similarity: {c['similarity']:.2f})\n{c['content']}")
    return "\n\n".join(parts) if parts else "No similar past cases found."


def run_triage(conn, alert_id: int) -> TriageResult:
    audit_steps: list[dict] = []

    # Step 1: Fetch raw alert
    with conn.cursor() as cur:
        cur.execute(
            """SELECT a.raw_narrative, t.sender_id, a.created_at, a.typology,
                      e.country
               FROM alerts a
               JOIN transactions t ON t.id = a.transaction_id
               JOIN entities e ON e.id = t.sender_id
               WHERE a.id = %s""",
            (alert_id,),
        )
        row = cur.fetchone()
    if not row:
        raise ValueError(f"Alert {alert_id} not found")
    raw_narrative, sender_id, created_at, typology, country = row
    alert_timestamp = created_at.strftime("%Y-%m-%d %H:%M UTC") if created_at else "unknown"
    jurisdiction = country or "unknown"

    # Step 2: Log raw alert
    curr_hash = log_step(conn, alert_id, "raw_alert", {"narrative_length": len(raw_narrative)})
    audit_steps.append({"step": "raw_alert", "hash": curr_hash})

    # Step 3: Redact
    tokenized_narrative, token_map = redact(raw_narrative)

    # Step 4: Log redaction
    curr_hash = log_step(conn, alert_id, "redaction", {"token_count": len(token_map)})
    audit_steps.append({"step": "redaction", "hash": curr_hash})

    # Step 5: Embed tokenized narrative
    alert_embedding = embed(tokenized_narrative)

    # Step 6: Retrieve entity history, regulations, similar cases
    entity_history_text, sql_executed = get_entity_history(conn, sender_id)
    regs = search_regulations(conn, tokenized_narrative, top_k=3)
    similar_cases = find_similar_cases(conn, alert_id, alert_embedding, top_k=3)

    # Step 7: Log retrieval
    curr_hash = log_step(conn, alert_id, "retrieval", {
        "reg_ids": [r["id"] for r in regs],
        "case_ids": [c["id"] for c in similar_cases],
    })
    audit_steps.append({"step": "retrieval", "hash": curr_hash})

    # Step 8: Build prompts
    user_prompt = USER_PROMPT_TEMPLATE.format(
        alert_id=alert_id,
        alert_timestamp=alert_timestamp,
        jurisdiction=jurisdiction,
        tokenized_alert_narrative=tokenized_narrative,
        entity_transaction_history=entity_history_text,
        similar_past_cases=_format_similar_cases(similar_cases),
        regulatory_excerpts=_format_regulations(regs),
    )

    # Step 9: Call LLM
    client = get_llm_client()
    brief = client.triage(SYSTEM_PROMPT, user_prompt)

    # Step 10: Log LLM response
    curr_hash = log_step(conn, alert_id, "llm_response", brief.model_dump())
    audit_steps.append({"step": "llm_response", "hash": curr_hash})

    # Step 11: Rehydrate text fields
    brief_dict = brief.model_dump()
    brief_dict["sar_narrative_draft"] = rehydrate(brief_dict["sar_narrative_draft"], token_map)
    brief_dict["reasoning_summary"] = rehydrate(brief_dict["reasoning_summary"], token_map)
    for flag in brief_dict["red_flags"]:
        flag["description"] = rehydrate(flag["description"], token_map)
    brief = TriageBrief(**brief_dict)

    # Step 12: Log rehydration + update alert status
    curr_hash = log_step(conn, alert_id, "rehydration", {"complete": True})
    audit_steps.append({"step": "rehydration", "hash": curr_hash})

    with conn.cursor() as cur:
        cur.execute("UPDATE alerts SET status='reviewed' WHERE id=%s", (alert_id,))
    conn.commit()

    return TriageResult(
        brief=brief,
        token_map=token_map,
        audit_steps=audit_steps,
        sql_executed=sql_executed,
        raw_narrative=raw_narrative,
        tokenized_narrative=tokenized_narrative,
    )
