[theme]
base = "light"
primaryColor = "#0297C8"
backgroundColor = "#F7F8FA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#0A1628"
font = "sans serif"

[server]
headless = true
runOnSave = true

[browser]
gatherUsageStats = false
